Match User scry-ops
    AuthenticationMethods publickey
    PasswordAuthentication no
    KbdInteractiveAuthentication no
    PermitTTY no
    X11Forwarding no
    AllowTcpForwarding no
    PermitTunnel no
    GatewayPorts no
    PermitUserEnvironment no
    ForceCommand /opt/scry-ops/bin/scry-dispatch
